steps:
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args: 
    - "-c"
    -  |
       echo "-== APT-GET UPDATE==-"
       apt-get -y update

       echo "-== APT-GET TERRAFORM AND INSTALL TERRAFORM ==-"
       apt-get install software-properties-common gnupg2
       curl https://apt.releases.hashicorp.com/gpg | gpg --dearmor > hashicorp.gpg
       install -o root -g root -m 644 hashicorp.gpg /etc/apt/trusted.gpg.d/
       apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com focal main"
       apt-get -y install terraform
       terraform version

       echo "-==Change the working directory ==-"
       cd  /workspace/terraform

       echo "-== INIT TF ==-"
       terraform init -backend-config=backend.conf -reconfigure \
       && terraform plan -var-file=./input.tfvars -out=./tfplan -lock=true \
       && terraform apply -auto-approve
    env:
      - 'CLOUDSDK_CORE_PROJECT=geczra-380202'
options:
  logging: CLOUD_LOGGING_ONLY