name: Backend CI [dev]

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  everbyte-api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Free disk space
        run: |
            df -h /
            sudo swapoff -a
            sudo apt clean
            docker image ls -aq
            docker rmi $(docker image ls -aq)
            find ~/work/_temp -name "cache.tgz" -exec rm -f {} \;
            sudo rm -rf "/usr/local/share/boost"
            sudo rm -rf "$AGENT_TOOLSDIRECTORY"
            df -h /

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
        
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
            context: .
            file: ./.deploy/api/Dockerfile
            # load: true
            platforms: linux/amd64
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            push: true
            # cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}
            # cache-to: type=inline

      # - name: Docker images list
      #   run: |
      #       sudo docker image list

      # - name: Push to Github Registry
      #   run: |
      #       docker push ${{ steps.meta.outputs.tags }}

